[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "zcurvepy"
authors = [{name = "TUBIC", email = "fgao@tju.edu.cn"}]
dynamic = ["version", "description"]
